resources:
  - ../../base

configMapGenerator:
  - name: pass-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=7532385874d23b5be6a08095e5b19a88e4757abc

  - name: pass-summary-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=7532385874d23b5be6a08095e5b19a88e4757abc

  - name: pass-image-api-config
    behavior: merge
    literals:
      - DD_ENV=dev
      - DD_VERSION=7532385874d23b5be6a08095e5b19a88e4757abc

images:
  - name: ghcr.io/joepeeples/sdlc-gitops-sample-stack/pass-api
    newTag: "7532385874d23b5be6a08095e5b19a88e4757abc"

  - name: ghcr.io/joepeeples/sdlc-gitops-sample-stack/pass-summary-api
    newTag: "7532385874d23b5be6a08095e5b19a88e4757abc"

  - name: ghcr.io/joepeeples/sdlc-gitops-sample-stack/pass-image-api
    newTag: "7532385874d23b5be6a08095e5b19a88e4757abc"
